title: Mike
description_en: writing from an uncertain existence
description_zh: 一个不确定的存在的书写
url: "https://oclwmike.github.io"
baseurl: ""
author: Mike

# Plugins
plugins:
  - jekyll-feed

future: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .git

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
